#!/usr/bin/env python3
"""Using dictionaries challenge"""

def main(): 
    """runtime function"""

    # dictionary for marvel characters
    marvelchars= {
    "Starlord":
    {"real name": "peter quill",
    "powers": "dance moves",
    "archenemy": "Thanos"},

    "Mystique":
    {"real name": "raven darkholme",
    "powers": "shape shifter",
    "archenemy": "Professor X"},

    "Hulk":
    {"real name": "bruce banner",
    "powers": "super strength",
    "archenemy": "adrenaline"}
                }

    # get user input for the character name
    char_name = input("Which character do you want to know about? (Starlord, Mystique, Hulk): " )

    # get user input for the character stat they want more info about
    char_stat = input("What statistic do you want to know about? (real name, powers, archenemy): ")

    # this will break if the user does not use actual keys 
    print(char_name  + "'s " + char_stat + " is: " + marvelchars[char_name][char_stat])

# call our main function
if __name__ == "__main__":
    main()

